logging:
  level:
    org.apache.kafka: info

server:
  port: 8080


googleHome:
  url: "http://localhost:1880"

cluster:
  autoCreateTopic: true
  bootstrapServers: "localhost:9093"
  securityProtocol: "PLAINTEXT"
  ssl:
    key-store-location: ""
    key-password: ""
    key-store-password: ""
    trust-store-location: ""
    trust-store-password: ""
  topic:
    minIsr: "1"
    partitions: "2"
    replicationFactor: "1"
    retentionMs: "3600000"
    segmentMs: "86400000"
    ifttt:
      name: ifttt
    notifications:
      name: notifications
    gitlab:
      name: pipeline
  gitlab:
    token: 91da49868407c3e269927d21bcfdc0
    refName: master
    projectId: 12410898
  producer:
    clientId: "ifttt-adapter-producer"
  consumer:
    enabled: true
    clientId: "ifttt-adapter-consumer"
    group-id: "io.axual.app.adapter.ifttt"

